mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - AUTH=yes
    - MONGODB_ADMIN_USER=root
    - MONGODB_ADMIN_PASS=password
    - MONGODB_APPLICATION_DATABASE=airdata-db
  volumes:
    - ./data/db:/data/db
  ports:
    - 27018:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet